server:
  port: 8082
  servlet:
    path: /stag
    session:
      timeout: 3600
  address: 127.0.0.1
  error:
    path: /error
#  env
my:
  name: spring-boot-stag
  date: 2019-03-22
  number: ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi, i`m ${my.name}
# log
logging:
  level:
    root: INFO
    org: INFO
    com.demo.mavenTutorial.controller: INFO